# Generated by Django 5.0.4 on 2024-04-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('mail_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('user_name', models.TextField(max_length=20)),
                ('mob', models.IntegerField(max_length=10)),
                ('fav_category', models.TextField(max_length=15)),
                ('fav_author1', models.TextField(max_length=20)),
                ('fav_author2', models.TextField(max_length=20)),
                ('fav_author3', models.TextField(max_length=20)),
                ('fav_book1', models.TextField(max_length=20)),
                ('fav_book2', models.TextField(max_length=20)),
                ('fav_book3', models.TextField(max_length=20)),
                ('offer', models.TextField(default='None')),
            ],
        ),
    ]
