# Generated by Django 5.0.4 on 2024-04-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='mob',
        ),
    ]
