# Generated by Django 5.0.4 on 2024-04-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_table_mob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='mob',
            field=models.IntegerField(null=True),
        ),
    ]
