# Generated by Django 5.0.4 on 2024-04-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_table_mob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_table',
            new_name='pageuser',
        ),
    ]
