# Generated by Django 5.0.4 on 2024-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_pageuser_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageuser',
            name='fav_author1',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pageuser',
            name='fav_author2',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pageuser',
            name='fav_author3',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pageuser',
            name='fav_category',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pageuser',
            name='mail_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pageuser',
            name='mob',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='pageuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
