# Generated by Django 5.0.4 on 2024-04-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_pageuser_fav_author1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageuser',
            name='fav_author3',
        ),
        migrations.RemoveField(
            model_name='pageuser',
            name='fav_book3',
        ),
    ]
