# Generated by Django 5.0.4 on 2024-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_pageuser_fav_author3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect_point',
            fields=[
                ('coll_id', models.CharField(primary_key=True, serialize=False)),
                ('coll_pname', models.TextField(max_length=30)),
                ('coll_plink', models.CharField(max_length=50)),
            ],
        ),
    ]
