# Generated by Django 5.0.4 on 2024-04-09 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_collect_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_table',
            fields=[
                ('book_id', models.CharField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('author', models.TextField(max_length=20)),
                ('review', models.TextField()),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('coin', models.IntegerField(blank=True, null=True)),
                ('category', models.TextField(max_length=10)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('f_pic', models.ImageField(null=True, upload_to='images/')),
                ('b_pic', models.ImageField(null=True, upload_to='images/')),
                ('c_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.collect_point')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pageuser')),
            ],
        ),
    ]
