# Generated by Django 5.0.4 on 2024-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_book_table_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
