# Generated by Django 5.0.4 on 2024-04-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_exchange_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_table',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
