# Generated by Django 5.0.4 on 2024-04-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_exchange_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageuser',
            name='fav_author1',
        ),
        migrations.RemoveField(
            model_name='pageuser',
            name='fav_author2',
        ),
        migrations.RemoveField(
            model_name='pageuser',
            name='fav_book1',
        ),
        migrations.RemoveField(
            model_name='pageuser',
            name='fav_book2',
        ),
    ]
