# Generated by Django 5.0.4 on 2024-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_pageuser_fav_author1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange_table',
            name='readshare_status',
        ),
        migrations.RemoveField(
            model_name='exchange_table',
            name='status',
        ),
        migrations.AddField(
            model_name='exchange_table',
            name='acc_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange_table',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange_table',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange_table',
            name='rej_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange_table',
            name='req_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange_table',
            name='ret_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange_table',
            name='ret_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
