# Generated by Django 5.0.4 on 2024-04-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_exchange_table_rej_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange_table',
            name='ret_acc_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
