# Generated by Django 5.0.4 on 2024-04-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_exchange_table_ret_acc_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange_table',
            name='ret_acc_time',
        ),
    ]
