# Generated by Django 5.0.4 on 2024-04-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_exchange_table_ret_acc_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
