# Generated by Django 5.0.4 on 2024-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_book_table_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange_table',
            name='book_user_note',
            field=models.TextField(default='Hey...'),
        ),
        migrations.AddField(
            model_name='exchange_table',
            name='user_note',
            field=models.TextField(default='Hey...'),
        ),
    ]
