# Generated by Django 5.0.4 on 2024-04-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_exchange_table_book_user_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_table',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(max_length=30)),
                ('note', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.book_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pageuser')),
            ],
        ),
    ]
