# Generated by Django 5.0.4 on 2024-04-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_report_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='category',
            field=models.TextField(max_length=20),
        ),
        migrations.CreateModel(
            name='suggest_table',
            fields=[
                ('sugg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(max_length=10)),
                ('topic', models.TextField(max_length=30)),
                ('desc', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pageuser')),
            ],
        ),
    ]
