# Generated by Django 5.0.4 on 2024-04-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_book_table_category_suggest_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect_point',
            name='coll_plink',
            field=models.TextField(),
        ),
    ]
