# Generated by Django 5.0.4 on 2024-05-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_collect_point_coll_plink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageuser',
            name='coin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
