# Generated by Django 5.0.4 on 2024-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_pageuser_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageuser',
            name='coin',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
