# Generated by Django 5.0.4 on 2024-05-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_pageuser_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect_point',
            name='coll_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('pay_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('upi_id', models.CharField(max_length=50)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(default='Pending')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.pageuser')),
            ],
        ),
    ]
