# Generated by Django 5.0.4 on 2024-05-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_collect_point_coll_id_payment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_table',
            name='amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
