# Generated by Django 5.0.4 on 2024-05-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_payment_table_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='state',
            field=models.TextField(default='Active'),
        ),
    ]
