# Generated by Django 5.0.4 on 2024-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_book_table_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageuser',
            name='verify',
            field=models.TextField(default='None'),
        ),
    ]
