# Generated by Django 5.0.4 on 2024-05-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_pageuser_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageuser',
            name='coin',
            field=models.IntegerField(default=2),
        ),
    ]
