# Generated by Django 5.0.4 on 2024-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_pageuser_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageuser',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
