# Generated by Django 5.0.4 on 2024-05-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_pageuser_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageadmin',
            fields=[
                ('mail_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
