# Generated by Django 5.0.4 on 2024-05-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_delete_offer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=10)),
                ('coin', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
