# Generated by Django 5.0.4 on 2024-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_offer_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='book_table',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
