# Generated by Django 5.0.4 on 2024-05-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_delete_post_book_table_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
