# Generated by Django 5.0.4 on 2024-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_book_table_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange_table',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
