# Generated by Django 5.0.4 on 2024-05-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_exchange_table_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange_table',
            name='slug',
        ),
    ]
