# Generated by Django 5.0.4 on 2024-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_remove_exchange_table_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='image2',
            field=models.BinaryField(null=True),
        ),
    ]
