# Generated by Django 5.0.4 on 2024-05-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_book_table_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_table',
            name='image2',
        ),
    ]
